In [ ]:
# libraries for numerical
import pandas as pd  
import numpy as np
# libraries for machine learning
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

In [ ]:
pharma_data = pd.read_csv('https://raw.githubusercontent.com/dphi-official/Datasets/master/pharma_data/Training_set_begs.csv')

In [ ]:
pharma_data.head()

   ID_Patient_Care_Situation  ...  Survived_1_year
0                      22374  ...                0
1                      18164  ...                1
2                       6283  ...                0
3                       5339  ...                1
4                      33012  ...                1

[5 rows x 18 columns]

In [ ]:
pharma_data['Treated_with_drugs'] = pharma_data['Treated_with_drugs'].fillna(pharma_data['Treated_with_drugs'].mode()[0])
pharma_data.head()

   ID_Patient_Care_Situation  ...  Survived_1_year
0                      22374  ...                0
1                      18164  ...                1
2                       6283  ...                0
3                       5339  ...                1
4                      33012  ...                1

[5 rows x 18 columns]

In [ ]:
pharma_data['Patient_Smoker'].isnull().sum()

0

In [ ]:
df=pharma_data
print(df)
is_NaN = df. isnull()
row_has_NaN = is_NaN. any().sum()
rows_with_NaN = [row_has_NaN]
print(rows_with_NaN)

       ID_Patient_Care_Situation  ...  Survived_1_year
0                          22374  ...                0
1                          18164  ...                1
2                           6283  ...                0
3                           5339  ...                1
4                          33012  ...                1
...                          ...  ...              ...
23092                      15613  ...                0
23093                      15503  ...                1
23094                       2167  ...                0
23095                      31646  ...                1
23096                       3947  ...                0

[23097 rows x 18 columns]
[8]

In [ ]:
df = pd.DataFrame(pharma_data)
df['Treated_with_drugs'].str.get_dummies(sep=' ')

       DX1  DX2  DX3  DX4  DX5  DX6
0        0    0    0    0    0    1
1        0    1    0    0    0    0
2        0    0    0    0    0    1
3        1    0    0    0    0    0
4        0    0    0    0    0    1
...    ...  ...  ...  ...  ...  ...
23092    0    1    0    1    0    0
23093    0    0    0    0    0    1
23094    0    0    0    0    0    1
23095    0    0    1    0    0    0
23096    0    0    0    0    0    1

[23097 rows x 6 columns]

In [ ]:
pharma_data = pd.get_dummies(pharma_data, columns=['Treated_with_drugs'])

In [ ]:
pharma_data['Patient_mental_condition'] = pharma_data['Patient_mental_condition'].fillna(pharma_data['Patient_mental_condition'].mode()[0])
pharma_data.head()

   ID_Patient_Care_Situation  ...  Treated_with_drugs_DX6
0                      22374  ...                       1
1                      18164  ...                       0
2                       6283  ...                       1
3                       5339  ...                       0
4                      33012  ...                       1

[5 rows x 49 columns]

In [ ]:
pharma_data['Patient_mental_condition'] = pharma_data['Patient_mental_condition'].fillna(pharma_data['Patient_mental_condition'].mode()[0])
pharma_data.head()

   ID_Patient_Care_Situation  ...  Treated_with_drugs_DX6
0                      22374  ...                       1
1                      18164  ...                       0
2                       6283  ...                       1
3                       5339  ...                       0
4                      33012  ...                       1

[5 rows x 49 columns]

In [ ]:
df = pd.DataFrame(pharma_data)
df['Patient_mental_condition'].str.get_dummies(sep=' ')

       Stable
0           1
1           1
2           1
3           1
4           1
...       ...
23092       1
23093       1
23094       1
23095       1
23096       1

[23097 rows x 1 columns]

In [ ]:
pharma_data = pd.get_dummies(pharma_data, columns=['Patient_mental_condition'])

In [ ]:
pharma_data['Patient_Smoker'] = pharma_data['Patient_Smoker'].fillna(pharma_data['Patient_Smoker'].mode()[0])
pharma_data['Patient_Smoker'].replace(['Cannot say'],'NO', inplace = True)
pharma_data.head()

   ID_Patient_Care_Situation  ...  Patient_mental_condition_Stable
0                      22374  ...                                1
1                      18164  ...                                1
2                       6283  ...                                1
3                       5339  ...                                1
4                      33012  ...                                1

[5 rows x 49 columns]

In [ ]:
df = pd.DataFrame(pharma_data)
df['Patient_Smoker'].str.get_dummies(sep=' ')

       NO  YES
0       0    1
1       0    1
2       0    1
3       1    0
4       1    0
...    ..  ...
23092   1    0
23093   1    0
23094   0    1
23095   0    1
23096   0    1

[23097 rows x 2 columns]

In [ ]:
pharma_data = pd.get_dummies(pharma_data, columns=['Patient_Smoker'])

In [ ]:
pharma_data['Patient_Rural_Urban'] = pharma_data['Patient_Rural_Urban'].fillna(pharma_data['Patient_Rural_Urban'].mode()[0])
pharma_data.head()

   ID_Patient_Care_Situation  ...  Patient_Smoker_YES
0                      22374  ...                   1
1                      18164  ...                   1
2                       6283  ...                   1
3                       5339  ...                   0
4                      33012  ...                   0

[5 rows x 50 columns]

In [ ]:
df = pd.DataFrame(pharma_data)
df['Patient_Rural_Urban'].str.get_dummies(sep=' ')

       RURAL  URBAN
0          0      1
1          1      0
2          1      0
3          0      1
4          1      0
...      ...    ...
23092      1      0
23093      1      0
23094      1      0
23095      1      0
23096      1      0

[23097 rows x 2 columns]

In [ ]:
pharma_data = pd.get_dummies(pharma_data, columns=['Patient_Rural_Urban'])

In [ ]:
#pharma_data.isnull().sum()

In [ ]:
pharma_data['A'] = pharma_data['A'].fillna(pharma_data['A'].mode()[0])
pharma_data['B'] = pharma_data['B'].fillna(pharma_data['B'].mode()[0])
pharma_data['C'] = pharma_data['C'].fillna(pharma_data['C'].mode()[0])
pharma_data['D'] = pharma_data['D'].fillna(pharma_data['D'].mode()[0])
pharma_data['E'] = pharma_data['E'].fillna(pharma_data['E'].mode()[0])
pharma_data['F'] = pharma_data['F'].fillna(pharma_data['F'].mode()[0])
pharma_data['Z'] = pharma_data['Z'].fillna(pharma_data['Z'].mode()[0])
pharma_data['Number_of_prev_cond'] = pharma_data['A']+pharma_data['B']+pharma_data['C']+pharma_data['D']+pharma_data['E']+pharma_data['F']+pharma_data['Z']

In [ ]:
pharma_data.head()

   ID_Patient_Care_Situation  ...  Patient_Rural_Urban_URBAN
0                      22374  ...                          1
1                      18164  ...                          0
2                       6283  ...                          0
3                       5339  ...                          1
4                      33012  ...                          0

[5 rows x 51 columns]

In [ ]:
X = pharma_data.drop('Survived_1_year', axis = 1)
y = pharma_data['Survived_1_year']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 8)

In [ ]:
model = LogisticRegression(solver= 'liblinear')
model.fit(X_train, y_train)

In [ ]:
pred_train = model.predict(X_train)

In [ ]:
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_train, pred_train)
cnf_matrix

array([[2564, 2576],
       [1310, 7408]])

In [ ]:
pred = model.predict(X_test)

In [ ]:
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test, pred)
cnf_matrix

array([[1696, 1658],
       [ 874, 5011]])

## Load New Test

In [ ]:
test_new = pd.read_csv('https://raw.githubusercontent.com/dphi-official/Datasets/master/pharma_data/Testing_set_begs.csv')

In [ ]:
test_new.head()

   ID_Patient_Care_Situation  Diagnosed_Condition  ...    Z Number_of_prev_cond
0                      19150                   40  ...  0.0                 2.0
1                      23216                   52  ...  0.0                 2.0
2                      11890                   50  ...  0.0                 2.0
3                       7149                   32  ...  0.0                 3.0
4                      22845                   20  ...  0.0                 1.0

[5 rows x 17 columns]

In [ ]:
test_new['Treated_with_drugs'] = test_new['Treated_with_drugs'].fillna(test_new['Treated_with_drugs'].mode()[0])
test_new.head()

   ID_Patient_Care_Situation  Diagnosed_Condition  ...    Z Number_of_prev_cond
0                      19150                   40  ...  0.0                 2.0
1                      23216                   52  ...  0.0                 2.0
2                      11890                   50  ...  0.0                 2.0
3                       7149                   32  ...  0.0                 3.0
4                      22845                   20  ...  0.0                 1.0

[5 rows x 17 columns]

In [ ]:
df = pd.DataFrame(test_new)
df['Treated_with_drugs'].str.get_dummies(sep=' ')

      DX1  DX2  DX3  DX4  DX5  DX6
0       0    0    1    0    0    0
1       0    0    0    0    0    1
2       0    0    0    1    1    0
3       0    0    0    0    0    1
4       0    0    1    0    0    0
...   ...  ...  ...  ...  ...  ...
9298    0    0    0    0    0    1
9299    1    0    0    0    0    0
9300    1    0    1    1    1    0
9301    0    0    0    1    0    0
9302    0    0    0    0    0    1

[9303 rows x 6 columns]

In [ ]:
test_new = pd.get_dummies(test_new, columns=['Treated_with_drugs'])

In [ ]:
test_new['Patient_mental_condition'] = test_new['Patient_mental_condition'].fillna(test_new['Patient_mental_condition'].mode()[0])
test_new.head()

   ID_Patient_Care_Situation  ...  Treated_with_drugs_DX6
0                      19150  ...                       0
1                      23216  ...                       1
2                      11890  ...                       0
3                       7149  ...                       1
4                      22845  ...                       0

[5 rows x 48 columns]

In [ ]:
df = pd.DataFrame(test_new)
df['Patient_mental_condition'].str.get_dummies(sep=' ')

      Stable
0          1
1          1
2          1
3          1
4          1
...      ...
9298       1
9299       1
9300       1
9301       1
9302       1

[9303 rows x 1 columns]

In [ ]:
test_new = pd.get_dummies(test_new, columns=['Patient_mental_condition'])

In [ ]:
test_new['Patient_Smoker'] = test_new['Patient_Smoker'].fillna(test_new['Patient_Smoker'].mode()[0])
test_new.head()

   ID_Patient_Care_Situation  ...  Patient_mental_condition_Stable
0                      19150  ...                                1
1                      23216  ...                                1
2                      11890  ...                                1
3                       7149  ...                                1
4                      22845  ...                                1

[5 rows x 48 columns]

In [ ]:
df = pd.DataFrame(test_new)
df['Patient_Smoker'].str.get_dummies(sep=' ')

      NO  YES
0      1    0
1      1    0
2      1    0
3      1    0
4      1    0
...   ..  ...
9298   1    0
9299   1    0
9300   0    1
9301   1    0
9302   0    1

[9303 rows x 2 columns]

In [ ]:
test_new = pd.get_dummies(test_new, columns=['Patient_Smoker'])

In [ ]:
test_new['Patient_Rural_Urban'] = test_new['Patient_Rural_Urban'].fillna(test_new['Patient_Rural_Urban'].mode()[0])
test_new.head()

   ID_Patient_Care_Situation  ...  Patient_Smoker_YES
0                      19150  ...                   0
1                      23216  ...                   0
2                      11890  ...                   0
3                       7149  ...                   0
4                      22845  ...                   0

[5 rows x 49 columns]

In [ ]:
test_new = pd.get_dummies(test_new, columns=['Patient_Rural_Urban'])

In [ ]:
test_new['A'] = test_new['A'].fillna(test_new['A'].mode()[0])
test_new['B'] = test_new['B'].fillna(test_new['B'].mode()[0])
test_new['C'] = test_new['C'].fillna(test_new['C'].mode()[0])
test_new['D'] = test_new['D'].fillna(test_new['D'].mode()[0])
test_new['E'] = test_new['E'].fillna(test_new['E'].mode()[0])
test_new['F'] = test_new['F'].fillna(test_new['F'].mode()[0])
test_new['Z'] = test_new['Z'].fillna(test_new['Z'].mode()[0])
test_new['Number_of_prev_cond'] = test_new['A']+test_new['B']+test_new['C']+test_new['D']+test_new['E']+test_new['F']+test_new['Z']

In [ ]:
test_new.head()

   ID_Patient_Care_Situation  ...  Patient_Rural_Urban_URBAN
0                      19150  ...                          0
1                      23216  ...                          1
2                      11890  ...                          0
3                       7149  ...                          1
4                      22845  ...                          0

[5 rows x 50 columns]

In [ ]:
Survived_1_year = model.predict(test_new)

In [ ]:
res = pd.DataFrame(Survived_1_year) #preditcions are nothing but the final predictions of your model on input features of your new unseen test data
res.index = test_new.index # its important for comparison. Here "test_new" is your new test dataset
res.columns = ["Survived_1_year"]

# To download the csv file locally
from google.colab import files
res.to_csv('prediction_results_HP.csv')         
files.download('prediction_results_HP.csv')